name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
 
  surefire:
    # Name the Job
    name: Surefire
    # Set the type of machine to run on
    runs-on: ubuntu-16.04
    steps:
     
       # Checks out a copy of your repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cache M2
        id: cache-m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: local-m2-repo
      
      # SWTBot Tests  
      - name: Setup Build Environment
        run: ./bash/setup.sh
      
      - name: Build Checkstyle Development
        run: |
          ls -l ~/.m2
          ./bash/maven_build.sh -j checkstyle -p development
        
      
 
