name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
 
  surefire:
    # Name the Job
    name: Surefire
    # Set the type of machine to run on
    runs-on: ubuntu-16.04
      steps:
       # Checks out a copy of your repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      # SWTBot Tests  
      - name: Start xvfb Server
        run: |
         sudo apt-get update
         sudo apt-get install xvfb metacity
         export DISPLAY=:99.0
         Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
         metacity --sm-disable --replace 2> metacity.err &
         ./bash/setup.sh
         ./bash/maven_build.sh -j surecoverage -p development
        
      
 
